version: '2'

services:
  master:
    build: .
    hostname: master
    volumes:
      - ./exareme-distribution/target/exareme:/root/exareme:ro
      - ./bootstrap.sh:/tmp/entrypoint.sh
    ports:
      - "9090:9090"
    working_dir: /root/exareme/
    entrypoint: /tmp/entrypoint.sh
    links:
      - rawdb
  worker:
    build: .
    volumes:
      - ./exareme-distribution/target/exareme:/root/exareme:ro
      - ./bootstrap.sh:/tmp/entrypoint.sh
    working_dir: /root/exareme/
    entrypoint: /tmp/entrypoint.sh
    environment:
      - EXAREME_MASTER=master
    links:
      - master
      - rawdb
  rawdb:
    image: raw-sniffer
    volumes:
      - ./rawdb_datasets:/datasets:ro
    ports:
      - "54321:54321"
